/**
 * Knowledge dimension: vocabulary — Slice 7.2 (ADR-0041).
 *
 * Condensed glossary of the project's domain terms. Goes right after
 * `identity` in the system prompt so the LLM speaks the same language
 * the user does ("recipe" not "function", "fan-out" not "iteration").
 *
 * Keep this lean. Prefer one-sentence definitions; link out for depth.
 * Source of truth: `docs/GLOSSARY.md`. When you add a term to the
 * glossary, mirror it here ONLY if the assistant needs to use it.
 */

export function buildVocabularyKnowledge(): string {
  return `## VOCABULARY

- **Reactive node** vs **non-reactive node**: reactive nodes (Text, Image, Number, Array, List, Iterators, Soul ID) are pure-config and re-run automatically on input change — zero spend. Non-reactive (LLM Text, Higgsfield Image Gen, Export) cost time/money and only run on explicit Run / Run-here / recipe \`run\` step.
- **Composite node** vs **expand**: a recipe instantiation. \`composite\` (default since Slice 6.6) drops a single node that internally runs the captured subgraph; \`expand\` drops the raw nodes. Composites have \`exposedInputs[]\` / \`exposedOutputs[]\` declaring the public surface.
- **Fan-out**: when an iterator-flagged node feeds a single-input downstream, the engine dispatches per-item executions in parallel (bounded by maxConcurrent=4). Used by Image Iterator + Text Iterator + Array.
- **Run-here**: trigger a partial workflow run that includes only a target node + its upstream ancestors. Per-node "▶" button on non-reactive nodes.
- **Generation**: a persisted output row in \`cookbook_generations\`. Auto-rehosted to Supabase Storage so external CDN URLs (Higgsfield) survive. Filterable in the Gallery.
- **Soul ID variants**: \`v2\` (newest, soul/v2/standard endpoint), \`cinema\` (soul/cinema), \`v1\` (legacy soul/character). Variant lives on the \`SoulIdRef\` and dispatches the right Higgsfield endpoint.
- **Asset Group**: a curated set of image assets in the library. An Image Iterator on canvas always points at one (post Slice 5.6).
- **Approval gate**: user preference; when on, runs that would spend > $0 prompt before kicking off. Applies to assistant-orchestrated runs too.
- **Continuity Builder** (multimodal arc): a sequential iterator. Unlike a normal iterator (parallel fan-out), it loops a video generator (Seedance) N times carrying state forward, so chunk N+1 continues chunk N. Two strategies: \`extension\` (feed the previous clip as a reference video) and \`frame-chain\` (extract the previous clip's last frame, feed it as the start image). Wire prompt + character image + song; the song is sliced into 15s windows for per-chunk lip-sync. Outputs the ordered clips.
- **Chunk**: one 15s segment of a continuous video. Seedance generates at most 15s per call, so a 4-minute song is ~16 chunks. Each chunk costs ~$2.25, so a full song is ~$36 — confirm with the user before long runs.
- **Video Concat**: remuxes (joins, no re-encode) the chunk array into one continuous MP4. Sits after the Continuity Builder.
- **Seedance Video**: ByteDance Seedance 2.0 via Fal — text/image/reference-to-video with native audio, lip-sync, person-swap, and video extension. The video generator the Continuity Builder loops. A **Model** dropdown in settings picks the tier (see below).
- **Seedance model tier** (\`model\`: \`standard\` / \`fast\` / \`mini\`): same Seedance 2.0 family at three cost/speed points — \`standard\` (best quality, up to 1080p), \`fast\` (lower latency + cost, ≤720p), \`mini\` (cheapest + quickest, ≤720p). Set via the **Model** dropdown in the node's \`⋯\` settings. All three tiers support BOTH reference mode and image-to-video (first/last frame). The old \`fast\` boolean still resolves to the fast tier for back-compat.
- **Fal Image**: one node, model picker — Nano Banana 2 (default), Flux 2, Seedream. Wire reference images to switch into edit mode.
- **Subtitles** (\`fal-veed-subtitles\` node): wraps Fal's \`veed/subtitles\` — wire a \`video\`, get the same clip back with auto-transcribed, styled subtitles burned in (\`video\` out). A style \`preset\` is required (default "simple"); presets split into BASIC (1x) and DYNAMIC (2x) pricing tiers. Optional \`language\` is the SOURCE audio language (better transcription, not the output language); optional \`translationLanguage\` subtitles in a different language (+$0.20/min). Cost: $0.10/min base · 2x above 1080p · 2x dynamic preset · +$0.20/min translation · min 1 min. Non-reactive (needs a Run). SRT import / vocabulary / per-tier style customization are deferred (not in v1).
- **DWPose** (\`fal-dwpose\` node): wraps Fal's \`fal-ai/dwpose/video\` — wire a \`video\`, get the same clip back with a DWPose pose drawn on top (\`video\` out). One \`drawMode\` setting: the \`*-pose\` modes (\`full-pose\`/\`body-pose\`/\`face-pose\`/\`hand-pose\`, default \`body-pose\`) draw the detected SKELETON; the \`*-mask\` modes (\`face-hand-mask\`/\`face-mask\`/\`hand-mask\`) output a white-on-black REGION mask instead. Typical use: make a pose/control video to drive a downstream motion-transfer step. Non-reactive (needs a Run). ~$0.0006/compute second.
- **TeleStyle V2** (\`fal-telestyle-v2\` node): style transfer wrapping Fal's \`fal-ai/telestyle-v2\` (Qwen-Image-Edit). TWO image inputs — \`content\` (subject/structure to keep) + \`style\` (look to borrow) → \`styled\` image out. NO prompt input: the prompt is auto-derived from both images by a VLM. Settings: \`loraScale\` (style strength 0..4, default 1.0 — lower keeps more of the content's original look) + \`outputFormat\` (png/jpeg). Result is re-hosted into our bucket. Non-reactive (needs a Run). Use it to restyle a character/photo into a reference's art style, material, lighting, or palette.
- **Performance Video** (recipe): the packaged singer-show pipeline — prompt + character + song -> Continuity Builder -> Video Concat. A composite recipe; drop it, wire the three inputs, Run.
- **Silent Video** (\`audio-to-video\` node, formerly "Audio → Silent Video"): renders an audio track OR a video's soundtrack as a solid-BLACK MP4 carrying the audio (wire a VIDEO and it keeps the sound, blanks the picture). Both inputs are \`multiple\` (a sliced array → one black clip per chunk). Output is a \`video\`. Lets you feed a song into Seedance's video slot (\`@Video1\`) as an AUDIO-ONLY reference — the black picture keeps the song from polluting the visuals (those come from keyframes) while the audio drives lip-sync/rhythm. The key primitive behind the black-screen-audio trick.
- **Seedance \`@Image[]\` socket**: in reference mode the Seedance node has, besides the numbered \`@Image1..\` sockets, ONE \`multiple\` image-array socket (handle id \`image\`, label \`@Image[]\`). Wire a whole image array into it (e.g. a Frames Extract's keyframes) and it fans into the \`@Image1..@ImageN\` series in order — one wire instead of N. Array entries land AFTER any individually-wired numbered sockets.
- **\`index\` drive input**: the way to point a multi-item node's PREVIEW at a chosen item by wiring a \`Number\` node. Video Slicer, Audio Slicer, Silent Video and Frames Extract each expose an \`index\` input (the List node's equivalent keeps handle id \`cursor\` for back-compat but its label also reads "index"). Wire one Number into several nodes' \`index\` to keep every chunk/keyframe ALIGNED on the same window — the pattern the multi-chunk singer recipe uses. It's \`viewOnly\`: it drives only what the body shows, never the node's output, so the engine ignores it in the cache hash — scrubbing the index never triggers a re-slice/re-decode. When a Number is driving it, the body's \`‹ N / M ›\` arrows lock (the value is external).
- **ByteDance singer-performance method** (recipes: "Singer Performance (ByteDance)" single-chunk + "Singer Performance (ByteDance · multi-chunk)"): the staged way to make a character sing a song without the references fighting. Stage 1 — character-swap Seedance: edit the performance video to swap in the character's identity (\`CHARACTER_SWAP_PROMPT\` anchors to a first/last keyframe; the multi-chunk recipe uses identity-only \`CHARACTER_SWAP_IDENTITY_ONLY_PROMPT\`). Stage 2 — decompose: extract ordered keyframes (Frames Extract, span) from the swapped clip + render the song as a black-screen MP4 (Silent Video). Stage 3 — keyframe-anchored singing Seedance: reference mode with the keyframes wired through the single \`@Image[]\` socket as @Image1…@ImageN and the black-screen song as @Video1, driven by \`KEYFRAME_ANCHORED_SINGING_PROMPT\`. The MULTI-CHUNK recipe drives both List pickers from ONE Number index so you step through a full song/video 15s window at a time, and exposes each window's first/last frames for stitching. Audio-as-black-video is what stops the song from overriding the visuals.`;
}
